In [3]:
import pandas as pd

# Carregando o arquivo que o Felipe limpou e salvou
df = pd.read_csv('../dados/processed/netflix_clean.csv')

# Exibe as primeiras 5 linhas para garantir que os dados abriram
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,years_to_netflix,duration_num
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Não Informado,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,1.0,90
1,s2,TV Show,Blood & Water,Não Informado,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,0.0,2
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Não Informado,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,0.0,1
3,s4,TV Show,Jailbirds New Orleans,Não Informado,Não Informado,Não Informado,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,0.0,1
4,s5,TV Show,Kota Factory,Não Informado,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,0.0,2

In [4]:
# Contando quantos títulos tem em cada classificação
contagem_rating = df['rating'].value_counts().reset_index()

# Renomeando as colunas para ficar organizado
contagem_rating.columns = ['Classificacao', 'Quantidade']

# Mostra o resultado na tela
contagem_rating

   Classificacao  Quantidade
0          TV-MA        3207
1          TV-14        2160
2          TV-PG         863
3              R         799
4          PG-13         490
5          TV-Y7         334
6           TV-Y         307
7             PG         287
8           TV-G         220
9             NR          80
10             G          41
11      TV-Y7-FV           6
12         NC-17           3
13            UR           3
14        74 min           1
15        84 min           1
16        66 min           1

In [5]:
import plotly.express as px

# Criando o gráfico de barras com as cores da Netflix
fig = px.bar(contagem_rating, 
             x='Classificacao', 
             y='Quantidade',
             title='Perfil de Público do Catálogo Netflix (Rating)',
             labels={'Classificacao': 'Classificação Indicativa', 'Quantidade': 'Total de Títulos'},
             template='plotly_dark',
             color='Quantidade', 
             color_continuous_scale='Reds')

fig.show()